default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kudos_plane_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: kudos_plane_test

production:
  primary: &production_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *production_primary
    database_tasks: false
  queue:
    <<: *production_primary
    database_tasks: true
  cable:
    <<: *production_primary
    database_tasks: false
